ARG DOCKER_REGISTRY_URL=docker.ceventis.de
ARG BASEIMAGE_VERSION=1.0
ARG NODE_VERSION=18
ARG PROJECT_DIR=

# Build layer
FROM ${DOCKER_REGISTRY_URL}/docker/baseimage/dotnet-node/sdk-onbuild:${BASEIMAGE_VERSION} AS build
